// Generated protobuf types
//
// This module re-exports all protobuf types generated by tonic-build.
// The actual code generation happens in build.rs at compile time.

// Include the generated proto code
// This will be populated by tonic-build during the build process
pub mod shared {
    pub mod event {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/shared.event.v1.rs"));
        }
    }
}

pub mod raw {
    pub mod npm {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/raw.npm.v1.rs"));
        }
    }
}

pub mod domain {
    pub mod package {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/domain.package.v1.rs"));
        }
    }
}

// Re-export commonly used types for convenience
pub use shared::event::v1::EventMeta;
pub use raw::npm::v1::NpmChange;
pub use domain::package::v1::{
    PackageUpserted, VersionUpserted, VersionYanked, PackageDeleted, IngestionError,
    Dependency,
};
