-- Audit log schema is managed by the application migration:
-- apps/ingestion/migrations/20260101000007_audit_log.sql
--
-- Keep this file as a no-op so fresh Docker volumes do not create a legacy
-- non-partitioned audit_log table before application migrations run.
