//! SLSA Provenance Implementation
//!
//! Based on SLSA (Supply-chain Levels for Software Artifacts) specification v1.0
//! for build provenance attestations.
//!
//! Reference: https://slsa.dev/spec/v1.0/

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use chrono::{DateTime, Utc};

// ═══════════════════════════════════════════════════════════════════════════
// SLSA BUILD LEVELS
// ═══════════════════════════════════════════════════════════════════════════

/// SLSA Build Track Levels (v1.0)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SlsaBuildLevel {
    /// Build L0: No guarantees - No SLSA
    L0,
    /// Build L1: Provenance exists - Attestation shows how package was built
    L1,
    /// Build L2: Hosted build platform - Signed provenance, generated by hosted build service
    L2,
    /// Build L3: Hardened builds - Isolated, ephemeral environment; signed, non-falsifiable provenance
    L3,
}

impl SlsaBuildLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            SlsaBuildLevel::L0 => "L0",
            SlsaBuildLevel::L1 => "L1",
            SlsaBuildLevel::L2 => "L2",
            SlsaBuildLevel::L3 => "L3",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            SlsaBuildLevel::L0 => "No SLSA - No provenance guarantees",
            SlsaBuildLevel::L1 => "Provenance exists - Build attestation available",
            SlsaBuildLevel::L2 => "Hosted build platform - Signed provenance from hosted service",
            SlsaBuildLevel::L3 => "Hardened builds - Isolated ephemeral environment, non-falsifiable provenance",
        }
    }

    pub fn requirements(&self) -> Vec<&'static str> {
        match self {
            SlsaBuildLevel::L0 => vec![],
            SlsaBuildLevel::L1 => vec![
                "Provenance exists",
                "Provenance is authentic",
                "Build process documented",
            ],
            SlsaBuildLevel::L2 => vec![
                "All L1 requirements",
                "Hosted build service",
                "Signed provenance",
                "Build service generates provenance",
            ],
            SlsaBuildLevel::L3 => vec![
                "All L2 requirements",
                "Isolated build environment",
                "Ephemeral environment",
                "Non-falsifiable provenance",
                "Hardened builds",
            ],
        }
    }

    /// Check if this level meets or exceeds the required level
    pub fn meets(&self, required: SlsaBuildLevel) -> bool {
        *self >= required
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// SLSA PROVENANCE PREDICATE (in-toto format)
// ═══════════════════════════════════════════════════════════════════════════

/// SLSA Provenance v1.0 predicate type
pub const SLSA_PROVENANCE_V1: &str = "https://slsa.dev/provenance/v1";

/// SLSA Provenance predicate (in-toto Statement wrapper)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlsaProvenance {
    /// in-toto Statement type
    #[serde(rename = "_type")]
    pub statement_type: String,
    /// Subject - the artifact(s) this provenance describes
    pub subject: Vec<Subject>,
    /// Predicate type URI
    #[serde(rename = "predicateType")]
    pub predicate_type: String,
    /// The actual provenance data
    pub predicate: ProvenancePredicate,
}

/// Subject of the in-toto statement (the built artifact)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Subject {
    /// Artifact name
    pub name: String,
    /// Cryptographic digests of the artifact
    pub digest: HashMap<String, String>,
}

/// SLSA Provenance v1.0 predicate
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenancePredicate {
    /// Information about the build
    #[serde(rename = "buildDefinition")]
    pub build_definition: BuildDefinition,
    /// Information about the run
    #[serde(rename = "runDetails")]
    pub run_details: RunDetails,
}

// ═══════════════════════════════════════════════════════════════════════════
// BUILD DEFINITION
// ═══════════════════════════════════════════════════════════════════════════

/// Build definition - what was supposed to happen
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildDefinition {
    /// Build type URI
    #[serde(rename = "buildType")]
    pub build_type: String,
    /// External parameters - user-controlled inputs
    #[serde(rename = "externalParameters")]
    pub external_parameters: ExternalParameters,
    /// Internal parameters - builder-controlled inputs
    #[serde(rename = "internalParameters", skip_serializing_if = "Option::is_none")]
    pub internal_parameters: Option<HashMap<String, serde_json::Value>>,
    /// Resolved dependencies
    #[serde(rename = "resolvedDependencies", skip_serializing_if = "Option::is_none")]
    pub resolved_dependencies: Option<Vec<ResourceDescriptor>>,
}

/// External parameters for the build
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalParameters {
    /// Source repository
    pub repository: String,
    /// Git reference (branch, tag, commit)
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub git_ref: Option<String>,
    /// Build configuration file
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow: Option<String>,
    /// Additional inputs
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inputs: Option<HashMap<String, serde_json::Value>>,
}

/// Resource descriptor for dependencies and artifacts
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceDescriptor {
    /// URI of the resource
    pub uri: String,
    /// Cryptographic digests
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digest: Option<HashMap<String, String>>,
    /// Human-readable name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Download location
    #[serde(rename = "downloadLocation", skip_serializing_if = "Option::is_none")]
    pub download_location: Option<String>,
    /// Media type
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
    /// Content of the resource (for inline resources)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Annotations
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annotations: Option<HashMap<String, serde_json::Value>>,
}

// ═══════════════════════════════════════════════════════════════════════════
// RUN DETAILS
// ═══════════════════════════════════════════════════════════════════════════

/// Run details - what actually happened
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunDetails {
    /// The build service/platform
    pub builder: Builder,
    /// Build metadata
    pub metadata: BuildMetadata,
    /// Byproducts of the build
    #[serde(skip_serializing_if = "Option::is_none")]
    pub byproducts: Option<Vec<ResourceDescriptor>>,
}

/// Builder information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Builder {
    /// Builder ID (URI)
    pub id: String,
    /// Builder version
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<HashMap<String, String>>,
    /// Builder dependencies
    #[serde(rename = "builderDependencies", skip_serializing_if = "Option::is_none")]
    pub builder_dependencies: Option<Vec<ResourceDescriptor>>,
}

/// Build metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildMetadata {
    /// Build invocation ID
    #[serde(rename = "invocationId", skip_serializing_if = "Option::is_none")]
    pub invocation_id: Option<String>,
    /// Build start time
    #[serde(rename = "startedOn", skip_serializing_if = "Option::is_none")]
    pub started_on: Option<DateTime<Utc>>,
    /// Build finish time
    #[serde(rename = "finishedOn", skip_serializing_if = "Option::is_none")]
    pub finished_on: Option<DateTime<Utc>>,
}

// ═══════════════════════════════════════════════════════════════════════════
// PROVENANCE BUILDER
// ═══════════════════════════════════════════════════════════════════════════

/// Builder for constructing SLSA Provenance
pub struct ProvenanceBuilder {
    subjects: Vec<Subject>,
    build_type: String,
    external_params: ExternalParameters,
    internal_params: Option<HashMap<String, serde_json::Value>>,
    dependencies: Vec<ResourceDescriptor>,
    builder_id: String,
    builder_version: Option<String>,
    started_on: Option<DateTime<Utc>>,
    finished_on: Option<DateTime<Utc>>,
    invocation_id: Option<String>,
}

impl ProvenanceBuilder {
    pub fn new(builder_id: impl Into<String>, repository: impl Into<String>) -> Self {
        Self {
            subjects: Vec::new(),
            build_type: "https://slsa.dev/container-based-build/v0.1".to_string(),
            external_params: ExternalParameters {
                repository: repository.into(),
                git_ref: None,
                workflow: None,
                inputs: None,
            },
            internal_params: None,
            dependencies: Vec::new(),
            builder_id: builder_id.into(),
            builder_version: None,
            started_on: None,
            finished_on: None,
            invocation_id: None,
        }
    }

    /// Add a subject (built artifact)
    pub fn add_subject(mut self, name: impl Into<String>, sha256: impl Into<String>) -> Self {
        let mut digest = HashMap::new();
        digest.insert("sha256".to_string(), sha256.into());
        self.subjects.push(Subject {
            name: name.into(),
            digest,
        });
        self
    }

    /// Set the build type
    pub fn build_type(mut self, build_type: impl Into<String>) -> Self {
        self.build_type = build_type.into();
        self
    }

    /// Set the git reference
    pub fn git_ref(mut self, git_ref: impl Into<String>) -> Self {
        self.external_params.git_ref = Some(git_ref.into());
        self
    }

    /// Set the workflow
    pub fn workflow(mut self, workflow: impl Into<String>) -> Self {
        self.external_params.workflow = Some(workflow.into());
        self
    }

    /// Add a dependency
    pub fn add_dependency(mut self, uri: impl Into<String>, sha256: Option<String>) -> Self {
        let digest = sha256.map(|h| {
            let mut d = HashMap::new();
            d.insert("sha256".to_string(), h);
            d
        });
        self.dependencies.push(ResourceDescriptor {
            uri: uri.into(),
            digest,
            name: None,
            download_location: None,
            media_type: None,
            content: None,
            annotations: None,
        });
        self
    }

    /// Set builder version
    pub fn builder_version(mut self, version: impl Into<String>) -> Self {
        self.builder_version = Some(version.into());
        self
    }

    /// Set build timestamps
    pub fn timestamps(mut self, started: DateTime<Utc>, finished: DateTime<Utc>) -> Self {
        self.started_on = Some(started);
        self.finished_on = Some(finished);
        self
    }

    /// Set invocation ID
    pub fn invocation_id(mut self, id: impl Into<String>) -> Self {
        self.invocation_id = Some(id.into());
        self
    }

    /// Build the provenance
    pub fn build(self) -> SlsaProvenance {
        let builder_version = self.builder_version.map(|v| {
            let mut m = HashMap::new();
            m.insert("version".to_string(), v);
            m
        });

        SlsaProvenance {
            statement_type: "https://in-toto.io/Statement/v1".to_string(),
            subject: self.subjects,
            predicate_type: SLSA_PROVENANCE_V1.to_string(),
            predicate: ProvenancePredicate {
                build_definition: BuildDefinition {
                    build_type: self.build_type,
                    external_parameters: self.external_params,
                    internal_parameters: self.internal_params,
                    resolved_dependencies: if self.dependencies.is_empty() {
                        None
                    } else {
                        Some(self.dependencies)
                    },
                },
                run_details: RunDetails {
                    builder: Builder {
                        id: self.builder_id,
                        version: builder_version,
                        builder_dependencies: None,
                    },
                    metadata: BuildMetadata {
                        invocation_id: self.invocation_id,
                        started_on: self.started_on,
                        finished_on: self.finished_on,
                    },
                    byproducts: None,
                },
            },
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// PROVENANCE VERIFIER
// ═══════════════════════════════════════════════════════════════════════════

/// Result of provenance verification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceVerification {
    /// Whether verification passed
    pub valid: bool,
    /// Achieved SLSA level
    pub slsa_level: SlsaBuildLevel,
    /// Verification details
    pub details: Vec<VerificationCheck>,
    /// Errors encountered
    pub errors: Vec<String>,
    /// Warnings
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationCheck {
    pub name: String,
    pub passed: bool,
    pub message: Option<String>,
}

/// Provenance verifier
pub struct ProvenanceVerifier {
    /// Trusted builder IDs
    trusted_builders: Vec<String>,
    /// Required SLSA level
    required_level: SlsaBuildLevel,
}

impl ProvenanceVerifier {
    pub fn new(required_level: SlsaBuildLevel) -> Self {
        Self {
            trusted_builders: Vec::new(),
            required_level,
        }
    }

    /// Add a trusted builder
    pub fn trust_builder(mut self, builder_id: impl Into<String>) -> Self {
        self.trusted_builders.push(builder_id.into());
        self
    }

    /// Verify provenance
    pub fn verify(&self, provenance: &SlsaProvenance) -> ProvenanceVerification {
        let mut checks = Vec::new();
        let mut errors = Vec::new();
        let mut warnings = Vec::new();

        // Check 1: Valid statement type
        let valid_statement = provenance.statement_type == "https://in-toto.io/Statement/v1";
        checks.push(VerificationCheck {
            name: "Valid in-toto statement".to_string(),
            passed: valid_statement,
            message: if valid_statement { None } else { Some("Invalid statement type".to_string()) },
        });

        // Check 2: Valid predicate type
        let valid_predicate = provenance.predicate_type == SLSA_PROVENANCE_V1;
        checks.push(VerificationCheck {
            name: "Valid SLSA predicate".to_string(),
            passed: valid_predicate,
            message: if valid_predicate { None } else { Some("Invalid predicate type".to_string()) },
        });

        // Check 3: Has subjects
        let has_subjects = !provenance.subject.is_empty();
        checks.push(VerificationCheck {
            name: "Has subjects".to_string(),
            passed: has_subjects,
            message: if has_subjects { None } else { Some("No subjects defined".to_string()) },
        });

        // Check 4: Subjects have digests
        let subjects_have_digests = provenance.subject.iter().all(|s| !s.digest.is_empty());
        checks.push(VerificationCheck {
            name: "Subjects have digests".to_string(),
            passed: subjects_have_digests,
            message: if subjects_have_digests { None } else { Some("Some subjects missing digests".to_string()) },
        });

        // Check 5: Builder is trusted
        let builder_trusted = self.trusted_builders.is_empty() 
            || self.trusted_builders.contains(&provenance.predicate.run_details.builder.id);
        checks.push(VerificationCheck {
            name: "Builder is trusted".to_string(),
            passed: builder_trusted,
            message: if builder_trusted { None } else { 
                Some(format!("Builder {} not in trusted list", provenance.predicate.run_details.builder.id))
            },
        });

        // Check 6: Has build metadata
        let has_metadata = provenance.predicate.run_details.metadata.started_on.is_some();
        checks.push(VerificationCheck {
            name: "Has build timestamps".to_string(),
            passed: has_metadata,
            message: if has_metadata { None } else { Some("Missing build timestamps".to_string()) },
        });

        // Determine SLSA level
        let all_passed = checks.iter().all(|c| c.passed);
        let slsa_level = if !all_passed {
            SlsaBuildLevel::L0
        } else if builder_trusted && has_metadata {
            SlsaBuildLevel::L2
        } else {
            SlsaBuildLevel::L1
        };

        if !slsa_level.meets(self.required_level) {
            errors.push(format!(
                "Achieved {} but required {}",
                slsa_level.as_str(),
                self.required_level.as_str()
            ));
        }

        if !has_metadata {
            warnings.push("Missing build timestamps - cannot verify build freshness".to_string());
        }

        ProvenanceVerification {
            valid: all_passed && slsa_level.meets(self.required_level),
            slsa_level,
            details: checks,
            errors,
            warnings,
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// SLSA ASSESSMENT
// ═══════════════════════════════════════════════════════════════════════════

/// SLSA assessment result for a package
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlsaAssessment {
    /// Package identifier
    pub package_id: String,
    /// Achieved SLSA level
    pub level: SlsaBuildLevel,
    /// Whether provenance exists
    pub has_provenance: bool,
    /// Whether provenance is signed
    pub provenance_signed: bool,
    /// Builder information
    pub builder: Option<String>,
    /// Source repository
    pub source_repo: Option<String>,
    /// Assessment timestamp
    pub assessed_at: DateTime<Utc>,
    /// Improvement recommendations
    pub recommendations: Vec<String>,
}

impl SlsaAssessment {
    /// Generate recommendations for improving SLSA level
    pub fn generate_recommendations(level: SlsaBuildLevel) -> Vec<String> {
        match level {
            SlsaBuildLevel::L0 => vec![
                "Add build provenance generation to your CI/CD pipeline".to_string(),
                "Document your build process".to_string(),
                "Consider using GitHub Actions or similar for reproducible builds".to_string(),
            ],
            SlsaBuildLevel::L1 => vec![
                "Move to a hosted build service (GitHub Actions, GitLab CI, etc.)".to_string(),
                "Enable provenance signing".to_string(),
                "Ensure build service generates provenance automatically".to_string(),
            ],
            SlsaBuildLevel::L2 => vec![
                "Enable isolated build environments".to_string(),
                "Use ephemeral build runners".to_string(),
                "Implement hermetic builds".to_string(),
                "Enable non-falsifiable provenance".to_string(),
            ],
            SlsaBuildLevel::L3 => vec![
                "Maintain current security posture".to_string(),
                "Consider additional supply chain security measures".to_string(),
            ],
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slsa_level_comparison() {
        assert!(SlsaBuildLevel::L3 > SlsaBuildLevel::L2);
        assert!(SlsaBuildLevel::L2 > SlsaBuildLevel::L1);
        assert!(SlsaBuildLevel::L1 > SlsaBuildLevel::L0);
        
        assert!(SlsaBuildLevel::L3.meets(SlsaBuildLevel::L2));
        assert!(SlsaBuildLevel::L2.meets(SlsaBuildLevel::L1));
        assert!(!SlsaBuildLevel::L1.meets(SlsaBuildLevel::L2));
    }

    #[test]
    fn test_provenance_builder() {
        let provenance = ProvenanceBuilder::new(
            "https://github.com/actions/runner",
            "https://github.com/example/repo",
        )
        .add_subject("pkg:npm/example@1.0.0", "abc123def456")
        .git_ref("refs/heads/main")
        .workflow(".github/workflows/build.yml")
        .builder_version("2.0.0")
        .build();

        assert_eq!(provenance.subject.len(), 1);
        assert_eq!(provenance.predicate_type, SLSA_PROVENANCE_V1);
        assert_eq!(
            provenance.predicate.build_definition.external_parameters.repository,
            "https://github.com/example/repo"
        );
    }

    #[test]
    fn test_provenance_verification() {
        let provenance = ProvenanceBuilder::new(
            "https://github.com/actions/runner",
            "https://github.com/example/repo",
        )
        .add_subject("pkg:npm/example@1.0.0", "abc123def456")
        .timestamps(Utc::now(), Utc::now())
        .build();

        let verifier = ProvenanceVerifier::new(SlsaBuildLevel::L1)
            .trust_builder("https://github.com/actions/runner");

        let result = verifier.verify(&provenance);
        
        assert!(result.valid);
        assert!(result.slsa_level >= SlsaBuildLevel::L1);
    }

    #[test]
    fn test_slsa_assessment_recommendations() {
        let l0_recs = SlsaAssessment::generate_recommendations(SlsaBuildLevel::L0);
        assert!(l0_recs.len() >= 2);
        
        let l3_recs = SlsaAssessment::generate_recommendations(SlsaBuildLevel::L3);
        assert!(l3_recs.iter().any(|r| r.contains("Maintain")));
    }

    #[test]
    fn test_provenance_serialization() {
        let provenance = ProvenanceBuilder::new(
            "https://github.com/actions/runner",
            "https://github.com/example/repo",
        )
        .add_subject("test", "sha256hash")
        .build();

        let json = serde_json::to_string_pretty(&provenance).unwrap();
        assert!(json.contains("slsa.dev"));
        assert!(json.contains("in-toto"));
        
        // Roundtrip
        let parsed: SlsaProvenance = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.subject.len(), 1);
    }
}
